# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-25 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EmptyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StandardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard', max_length=32)),
                ('val', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbool', models.BooleanField(default=False)),
                ('mdate', models.DateField(default=datetime.date(2017, 11, 25))),
                ('mdatetime', models.DateTimeField(default=datetime.datetime(2017, 11, 25, 9, 41, 6))),
                ('mtime', models.TimeField(default=datetime.time(9, 52, 7))),
            ],
        ),
        migrations.AddField(
            model_name='citytest',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dantejcoder.RegionTest'),
        ),
    ]
